import type { Metadata } from "next";
import { Special_Gothic_Expanded_One } from "next/font/google";
import "./globals.css";

const gothic = Special_Gothic_Expanded_One({
  variable: "--font-gothic",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${gothic.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
